### ISSUE TITLE
model.feature_list function in OOD_Generate_Mahalanobis.py 

### ISSUE THREAD

**Issue by samunaai** [paaatcha/gram-ood#2]
Dear Andre,
Greetings. Hoping you are doing well!
I was hoping to ask one question about the model definitions used in `mahalanobis_and_odin/OOD_Generate_Mahalanobis.py`.
I noticed that in line 83, we are using a function called `feature_list` via `temp_list = model.feature_list(temp_x)[1]`?
However, this method is not currently defined in the models in `my_models`, such as `my_models.resnet_50`,
I was hoping to inquire regarding how you were able to define these functions? Just so I could maintain compatibility with the versions of PyTorch you used in torchvision.models.
Thank you so much!
Warm regards,

**Comment by paaatcha** [comment]
Hello @munachisonwadike. Sorry for the late reply.
I was investigating your problem and I identified the reason. In the email you have sent to us, Chamdramoulli has shared with the [original repository](https://github.com/chandramouli-sastry/deep_Mahalanobis_detector). The authors have coded the models in a different way. They've changed its structure to capture the features. You may find the `feature_list` method [here](https://github.com/chandramouli-sastry/deep_Mahalanobis_detector/blob/1384c127d5c77fbcddc07d61a2269d405088df73/models/resnet.py#L162).

The way we do it in this repository is different. We set a hook to get the features of interest. You may see it [here](https://github.com/paaatcha/gram-ood/blob/master/sk_resnet-50.ipynb) in the `Setting the hook register`cell. That's why you cannot find the method. Particularly I think using the hooker is better since we don't modify anything in the original model.

A quick solution: you may define the hook function similar to the one [here](https://github.com/paaatcha/gram-ood/blob/master/sk_resnet-50.ipynb) and capture the features. Another solution would be copying the models from the original repository.

Can you check it?

**Comment by samunaai** [comment]
Fantastic let me try

**Comment by samunaai** [comment]
Dear Andre @paaatcha,
Greetings! I hope this message finds you well.
Thank you so very much for your feedback. I have implemented some basic technique to extract the features from the same 5 layers of resnet as in the [original implementation](https://github.com/chandramouli-sastry/deep_Mahalanobis_detector/blob/1384c127d5c77fbcddc07d61a2269d405088df73/models/resnet.py#L162).  This can be found in my fork of the [`resnet_50.py` here](https://github.com/munachisonwadike/gram-ood/blob/master/my_models/resnet_50.py). I borrowed the `isinstance()` function used in the hooks, but I directly take those feature layers which were of interest, in the same way as was done in the original repo with the `feature_list` and `intermediate_forward` functions  (the first convolution layer after ReLU, and the other 4 resnet block layers)
However, I noticed that I am getting slightly different results from what was reported in your paper for the unbiased evaluation of resnet_50 using TNR (Mahalanobis). I attached the screenshots of the results below. Would the results still be within the margin of error? Also, I noticed that only TNR metric was provided in the paper for unbiased evaluation. Do the results from `OOD_Regression_Mahalanobis.py` correspond to the unbiased evaluation scores?
Thank you so much once again, and I look forward to hearing from you.
Warm regards,
![image](https://user-images.githubusercontent.com/22077758/137645555-ebedae7e-a9ab-490e-b9c0-4cb3cdd65a6c.png)

**Comment by samunaai** [comment]
Greetings @paaatcha! I hope this message finds you well.
Just a small addition: I also made an implementation of the `resnet_50.py` where I used hooks instead of directly taking the features. However when I try to use hooks as was done in the [`sk_resnet-50.ipynb`](https://github.com/munachisonwadike/gram-ood/blob/master/sk_resnet-50.ipynb), the hook function is using the criterion `if isinstance(layer, models.resnet.Bottleneck)`. However, this will return 16 layers of resnet, instead of just 5 layers that was done in the [original implementation](https://github.com/pokaxpoka/deep_Mahalanobis_detector/blob/master/models/resnet.py). The problem is that 16 layers becomes too heavy for the `sample_estimator` function in [`lib_generation.py`](https://github.com/munachisonwadike/gram-ood/blob/master/mahalanobis_and_odin/lib_generation.py), since it performs a lot of heavy matrix computations. This results in an OOM error on our relatively small GPU (screenshot below). 
Did you use a different `isinstance` criterion for your gram-ood and mahalanobis implementations? (i.e a different set of layers from which we hook the features?) Perhaps something closer to 5 features in total rather than 16 used in gram?
Thank you so much once again, and I look forward to hearing from you.
Warm regards,

![image](https://user-images.githubusercontent.com/22077758/137814623-6d16f208-294d-4c23-92dd-75ae122452aa.png)

**Comment by chandramouli-sastry** [comment]
The mahalanobis algorithm computes covariance matrices and that's costly:
using features only at the end of the resnet/densenet blocks works best for
mahalanobis.

**Comment by paaatcha** [comment]
> Greetings @paaatcha! I hope this message finds you well. Just a small addition: I also made an implementation of the `resnet_50.py` where I used hooks instead of directly taking the features. However when I try to use hooks as was done in the [`sk_resnet-50.ipynb`](https://github.com/munachisonwadike/gram-ood/blob/master/sk_resnet-50.ipynb), the hook function is using the criterion `if isinstance(layer, models.resnet.Bottleneck)`. However, this will return 16 layers of resnet, instead of just 5 layers that was done in the [original implementation](https://github.com/pokaxpoka/deep_Mahalanobis_detector/blob/master/models/resnet.py). The problem is that 16 layers becomes too heavy for the `sample_estimator` function in [`lib_generation.py`](https://github.com/munachisonwadike/gram-ood/blob/master/mahalanobis_and_odin/lib_generation.py), since it performs a lot of heavy matrix computations. This results in an OOM error on our relatively small GPU (screenshot below). Did you use a different `isinstance` criterion for your gram-ood and mahalanobis implementations? (i.e a different set of layers from which we hook the features?) Perhaps something closer to 5 features in total rather than 16 used in gram? Thank you so much once again, and I look forward to hearing from you. Warm regards,
> 
> ![image](https://user-images.githubusercontent.com/22077758/137814623-6d16f208-294d-4c23-92dd-75ae122452aa.png)

Hello @munachisonwadike! Sorry for the late reply, I'm super busy this week.
I was going to add @chandramouli-sastry to this conversation (he performed the experiments using ODIN and Mahalanobis), but he's already answered you.
